api_key: <Your API key>

real_time: True

data_series:
  core_pce_inf:
    label: 'Core PCE inflation'
    code: 'PCEPILFE'
    transformation: 'yoy-m'
    revision: 'get_rate'
    accumulate: 'period-over-period'
  unemployment:
    label: 'Unemployment'
    code: 'UNRATE'
  cbo_unemployment:
    label: 'CBO Unemployment'
    code: 'NROU'
    interpolate: 'linear'
  core_pce_real:
    label: 'Core PCE real'
    code: 'DPCCRAM1M225NBEA'
    accumulate: 'period-over-period'
    transformation: 'yoy-m'
  interest:
    label: 'FFR'
    code: 'FEDFUNDS'
    transformation: None