api_key: '<API key here>'
real_time: True

sample_start: '01-01-1990'
name_convention: 'tag'
store_vintage: True

data_series:
  consumer_sentiment:
    label: 'Consumer sentiment UM'
    code: 'UMCSENT'
    transformation: 'd12'
    interpolate: 'linear'
  core_pce_inf:
    label: 'Core PCE inflation'
    code: 'PCEPILFE'
    transformation: 'yoy-m'
    revision: 'get_rate'
    accumulate: 'period-over-period'
  unemployment:
    label: 'Unemployment'
    code: 'UNRATE'
  cbo_unemployment:
    label: 'CBO Unemployment'
    code: 'NROU'
    interpolate: 'linear'
  core_pce_real:
    label: 'Core PCE real'
    code: 'DPCCRAM1M225NBEA'
    accumulate: 'period-over-period'
    transformation: 'yoy-m'
  interest:
    label: 'FFR'
    code: 'FEDFUNDS'
    transformation: None